name: Push Code to EC2

on:
  push:
    branches:
      - main

jobs:
  push_to_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Add EC2 host key to known_hosts
        run: |
          ssh-keyscan -H $EC2_IP_ADDRESS >> ~/.ssh/known_hosts

      - name: Push code to EC2
        run: |
          # Load the private key from GitHub Secrets
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Set IP address and directory paths
          EC2_IP="$EC2_IP_ADDRESS"
          SOURCE_DIR="$GITHUB_WORKSPACE/"
          DEST_DIR="/var/www/html/wordpress/"

          # Use rsync with SSH key authentication and compression
          rsync -avz --delete-after --exclude='.git' -e "ssh -i private_key.pem" "$SOURCE_DIR" "ubuntu@$EC2_IP:$DEST_DIR"

          # Clean up the private key file
          rm private_key.pem

        env:
          EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
