name: Push Code to EC2

on:
  push:
    branches:
      - main

jobs:
  push_to_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

      - name: Push Code to EC2
        run: |
          rsync -avz --delete-after --exclude='.git' $GITHUB_WORKSPACE/ ubuntu@3.221.121.112:/var/www/html/wordpress/
